#
# Labtainer Dockerfile - targetb (he B: web loi, chi HTTP, SV pwn lay flag)
#
ARG registry
FROM $registry/labtainer.network
#
ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh
#
# Web stack + ping (khong Wazuh, khong modsec, khong SSH -> chi vao duoc qua HTTP)
RUN apt-get update && ( \
      apt-get install -y --no-install-recommends apache2 php libapache2-mod-php iputils-ping \
      || apt-get install -y --no-install-recommends apache2 libapache2-mod-php7.0 iputils-ping \
    ) ; rm -rf /var/lib/apt/lists/*
RUN systemctl enable apache2 2>/dev/null || true
#
ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /
#
RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo
#
USER $user_name
ENV HOME /home/$user_name
#
ADD $labdir/$imagedir/home_tar/home.tar $HOME
RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME
#
USER root
CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]
